apiVersion: v1
kind: Service
metadata:
  name: eks-service
  namespace: tomcat
  labels:
    app: tomcat
spec:
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
