---
- hosts: localhost
  tasks:
    - name: download tomcat server packages
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
        dest: /opt/
    - name: extract tomcat packages
      unarchive:
        src: /opt/apache-tomcat-10.0.27.tar.gz
        dest: /opt/
    - name: Copy the war file
      copy:
        src: /home/ubuntu/jenkins/workspace/integrate-sonar/starter-code/starter-code/target/demo-4.0.0-SNAPSHOT.war
        dest: /opt/apache-tomcat-10.0.27/webapps/
    - name: Start Tomcat
      shell: nohup /opt/apache-tomcat-10.0.27/bin/startup.sh
