---
- hosts: localhost
  become: root
  #gather_facts: no
  #become_user: ubuntu
  tasks:
    - name: download tomcat server packages
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
        dest: /usr/local/
    - name: extract tomcat packages
      unarchive:
        src: /usr/local/apache-tomcat-10.0.27.tar.gz
        dest: /opt/
        mode: '0777'
        #remote_src: yes
    - name: Copy the war file
      copy:
        #src: /var/lib/jenkins/workspace/ansible-pipeline/starter-code/starter-code/target/demo-4.0.0-SNAPSHOT.war
        src: /var/lib/jenkins/workspace/ansible/starter-code/starter-code/target/demo-4.0.0-SNAPSHOT.war
        dest: /opt/apache-tomcat-10.0.27/webapps/
        #remote_src: yes
    - name: change tomcat port number
      shell: sed -i 's/port="8080"/port="9090"/' /opt/apache-tomcat-10.0.27/conf/server.xml
    - name: Start Tomcat
      shell: nohup /opt/apache-tomcat-10.0.27/bin/startup.sh
