---
- hosts: localhost
  become: True
  tasks:
    - name: download tomcat server packages
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
        dest: /usr/local
    - name: extract tomcat packages
      unarchive:
        src: /usr/local/apache-tomcat-10.0.27.tar.gz
        dest: /usr/local
        remote_src: yes
    - name: Copy the war file
      copy:
        src: /tmp/demo.war
        dest: /usr/local/apache-tomcat-10.0.27/webapps/
        remote_src: yes
    - name: change tomcat port number
      shell: sed -i 's/port="8080"/port="9090"/' /usr/local/tomcat/conf/server.xml
    - name: Start Tomcat
      shell: nohup /usr/local/apache-tomcat-10.0.27/bin/startup.sh
