---
- hosts: localhost
  become: True
  tasks:
    - name: download tomcat server packages
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
        dest: /usr/local/
    - name: extract tomcat packages
      unarchive:
        src: /usr/local/apache-tomcat-10.0.27.tar.gz
        dest: /usr/local/
    - name: Copy the war file
      copy:
        src: /home/ubuntu/jenkins/workspace/integrate-sonar/starter-code/starter-code/target/demo-4.0.0-SNAPSHOT.war
        dest: /usr/local/apache-tomcat-10.0.27/webapps/
    - name: change tomcat port number
      shell: sed -i 's/port="8080"/port="9090"/' /usr/local/apache-tomcat-10.0.27/conf/server.xml
    - name: Start Tomcat
      shell: nohup /usr/local/apache-tomcat-10.0.27/bin/startup.sh
